# Generated by Django 4.2.2 on 2023-06-28 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_app', '0002_alter_computer_quantity_alter_computer_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerspecification',
            name='price_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000000.0)]),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='price_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(20000.0)]),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='ram',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
