# Generated by Django 4.2.2 on 2023-06-28 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_app', '0003_alter_computerspecification_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
